{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.fullname" . }}-service-monitor
  labels:
    release: {{ .Values.serviceMonitor.prometheusReleaseName }}
  {{- include "chart.labels" . | nindent 4 }}
  namespace: {{ .Values.serviceMonitor.namespace }}
spec:
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      control-plane: controller-manager
{{- end}}