apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "chart.fullname" . }}-health-check-operator-service-monitor
  labels:
    release: prometheus
  {{- include "chart.labels" . | nindent 4 }}
  namespace: monitoring
spec:
  endpoints:
  - path: /metrics
    port: metrics
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      control-plane: controller-manager