apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager-role
  labels:
  {{- include "chart.labels" . | nindent 4 }}
rules:
- apiGroups:
  - check.cloudders.com
  resources:
  - healthchecks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - check.cloudders.com
  resources:
  - healthchecks/finalizers
  verbs:
  - update
- apiGroups:
  - check.cloudders.com
  resources:
  - healthchecks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - check.cloudders.com
  resources:
  - notificationrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - check.cloudders.com
  resources:
  - notificationrules/finalizers
  verbs:
  - update
- apiGroups:
  - check.cloudders.com
  resources:
  - notificationrules/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "chart.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: health-check-operator
    app.kubernetes.io/part-of: health-check-operator
  {{- include "chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "chart.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "chart.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'