apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}-controller-manager-rest-service
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: health-check-operator
    app.kubernetes.io/part-of: health-check-operator
    control-plane: controller-manager
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.restService.type }}
  selector:
    control-plane: controller-manager
  {{- include "chart.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.restService.ports | toYaml | nindent 2 -}}